app: # 应用基本配置
  env: local # 环境名称 local test production
  port: 8888 # 服务监听端口号
  app_name: backend-app # 应用名称
  app_url: 127.0.0.1 # 应用域名

log:
  level: info # 日志级别
  root_dir: ./storage/logs # 日志根目录
  filename: app.log # 日志文件名称
  format: # 写入格式
  show_line: true # 时候显示调用行
  max_backups: 3 #旧文件的最大个数
  max_size: 500 # 旧文件最大大小 MB
  max_age: 28 #旧文件最大保留天数
  compress: true # 是否压缩

database:
  driver: mysql # 数据库驱动
  host: ops-mysql # 域名
  port: 3306 # 端口号
  database: ops_by_go # 数据库名称
  username: root # 用户名
  password: q1w2e3r4 # 密码
  charset: utf8mb4 # 编码格式
  max_idle_conns: 8 # 空闲连接池中连接的最大数量
  max_open_conns: 10 # 打开数据库连接的最大数量
  log_mode: info # 日志级别
  enable_file_log_writer: true # 是否启用日志文件
  log_filename: sql.log # 日志文件名称

jwt:
  secret: MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgyL/tft4a6NBfRe6raU1M5UUH+YZ4qe191WyRHDalLg+hRANCAASnpRLcB3jhwvHQbUUHPoei0Sia7Zl20YLkwWxMW0KkGz/72d4Ud9aElfmLvO1FNMNiSMkvtvMtVcucFIfPmLGI # 256对称加密秘钥
  jwt_ttl: 43200  # token有效期
  jwt_blacklist_grace_period: 10 # jwt在黑名单中的宽限时间，避免并发请求失败，s
  refresh_grace_period: 1800 # token自动刷新距离token失效的时间时间，s

redis:
  host: ops-redis  # 主机
  port: 6379 #端口
  db: 0 # 数据仓
  password: q1w2e3r4 # 密码

bitcaskDB:
  dir_path: ./storage/bitcaskdb # 日志根目录

